// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdrdyvyzrxrzmotarpzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcmR5dnl6cnhyem1vdGFycHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTkxMDQsImV4cCI6MjA1NjM5NTEwNH0.fnVUAn5CxuVcfjLjZ218aier4-hi-E8qu_6trk8mmtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);